t=input("t=")
v=input("v=")
x=input("x=")
y=input("y=")
print(("а) 5 10"),end="          ")
print("б) 100",int(t),end="          ")
print("в)",int(x),"25")
print("   7 cm",end="          ")
print("  1949",int(v),end="          ")
print(("  "),int(x),int(y))
