t=input("t=")
v=input("v=")
x=input("x=")
y=input("y=")
t=int(t)
v=int(v)
x=int(x)
y=int(y)
print(("а) 5 10"),end="          ")
print("б) 100",(t),end="          ")
print("в)",(x),"25")
print("   7 cm",end="          ")
print("  1949",(v),end="          ")
print(("  "),(x),(y))
